/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ebank.views;

import com.ebank.controllers.CustomerFormController;
import static com.ebank.main.CommonFunctions.showMsg;

/**
 *
 * @author Shan
 */
public class CustomerForm extends javax.swing.JFrame {

    private CustomerPage parent;
    private CustomerFormController controller;

    /**
     * Default constructor (for add operation)
     *
     * @param parent parent windows
     */
    public CustomerForm(CustomerPage parent) {
        controller = new CustomerFormController();
        initComponents();
        setLocationRelativeTo(null);
        customizelayout();
        this.parent = parent;
    }

    /**
     * Overloaded constructor for edit operation
     *
     * @param accountNo customer record that needs to be edited
     * @param parent parent windows
     */
    public CustomerForm(String accountNo, CustomerPage parent) {
        controller = new CustomerFormController();
        initComponents();
        customizelayout(accountNo);
        setLocationRelativeTo(null);
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_operation = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_customerId = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_birthdate = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_type = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_accountNo = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_sortCode = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_balance = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_card = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.cyan);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Account");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All fields are required");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(java.awt.Color.pink);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 20));

        btn_operation.setBackground(java.awt.Color.yellow);
        btn_operation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_operation.setText("Operation");
        btn_operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operationActionPerformed(evt);
            }
        });
        jPanel2.add(btn_operation);

        btn_cancel.setBackground(java.awt.Color.yellow);
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel3.setLayout(new java.awt.GridLayout(8, 0, 0, 15));
        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Customer Id: ");
        jPanel6.add(jLabel3);

        txt_customerId.setColumns(9);
        txt_customerId.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txt_customerId.setEnabled(false);
        jPanel6.add(txt_customerId);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 95, 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Name: ");
        jPanel7.add(jLabel4);

        txt_name.setColumns(10);
        txt_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(txt_name);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 45, 5));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Birth Date: ");
        jPanel8.add(jLabel5);

        txt_birthdate.setColumns(10);
        txt_birthdate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel8.add(txt_birthdate);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Address: ");
        jPanel9.add(jLabel6);

        txt_address.setColumns(10);
        txt_address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel9.add(txt_address);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 85, 5));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("Mobile: ");
        jPanel10.add(jLabel7);

        txt_mobile.setColumns(10);
        txt_mobile.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel10.add(txt_mobile);

        jPanel3.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 95, 5));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("Email: ");
        jPanel11.add(jLabel8);

        txt_email.setColumns(10);
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel11.add(txt_email);

        jPanel3.add(jPanel11);
        jPanel3.add(jPanel12);

        jTabbedPane1.addTab("Personal Details", jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(7, 0, 0, 15));
        jPanel4.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setText("Account Type: ");
        jPanel14.add(jLabel9);

        txt_type.setColumns(10);
        txt_type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel14.add(txt_type);

        jPanel4.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 38, 5));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("Account No: ");
        jPanel15.add(jLabel10);

        txt_accountNo.setColumns(10);
        txt_accountNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel15.add(txt_accountNo);

        jPanel4.add(jPanel15);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 58, 5));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Sort Code: ");
        jPanel16.add(jLabel11);

        txt_sortCode.setColumns(10);
        txt_sortCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel16.add(txt_sortCode);

        jPanel4.add(jPanel16);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 5));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setText("Balance: ");
        jPanel17.add(jLabel12);

        txt_balance.setColumns(10);
        txt_balance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_balance.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel17.add(txt_balance);

        jPanel4.add(jPanel17);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 118, 5));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel13.setText("Card: ");
        jPanel18.add(jLabel13);

        txt_card.setColumns(10);
        txt_card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel18.add(txt_card);

        jPanel4.add(jPanel18);
        jPanel4.add(jPanel19);

        jTabbedPane1.addTab("Account Details", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operationActionPerformed
        doOperation();
    }//GEN-LAST:event_btn_operationActionPerformed

    /**
     * Perform add/edit operation
     */
    private void doOperation() {
        int customerId = 0;
        try { // if customerId is not an int value
            customerId = Integer.parseInt(txt_customerId.getText());
        } catch (Exception e) {
            customerId = 0;
        }
        String name = txt_name.getText();
        String birthdate = txt_birthdate.getText();
        String address = txt_address.getText();
        String mobile = txt_mobile.getText();
        String email = txt_email.getText();
        String type = txt_type.getText();
        String accountNo = txt_accountNo.getText();
        String sortCode = txt_sortCode.getText();
        String balance = txt_balance.getText();
        String card = txt_card.getText();

        // check for empty fields
        if (!name.equals("") && !birthdate.equals("") && !address.equals("")
                && !mobile.equals("") && !email.equals("") && !type.equals("")
                && !accountNo.equals("") && !sortCode.equals("") && !balance.equals("")
                && !card.equals("")) {
            if (controller.syncCustomerAddEditOperation(customerId, name, birthdate,
                    address, mobile, email, type, accountNo, sortCode, balance, card)) {
                showMsg(0, 0, "Record successfully added/edited");
                this.dispose();
                String loggedInUser = parent.loggedInUser;
                parent.dispose();
                new CustomerPage(loggedInUser).setVisible(true);
            } else {
                showMsg(2, 2, "Something went wrong");
            }
        } else {
            showMsg(1, 1, "Please make sure you have filled all the fields");
        }
    }

    /**
     * Customize layout according to add operation
     */
    private void customizelayout() {
        this.setTitle("Add new customer");
        btn_operation.setText("Add");
        txt_customerId.setText("N/A");
    }

    /**
     * Customize layout according to edit operation
     *
     * @param accountNo accountNo of the record that needs to be edited
     */
    private void customizelayout(String accountNo) {
        this.setTitle("Edit customer");
        btn_operation.setText("Edit");
        String[] customerData = controller.getCustomerData(accountNo);
        txt_customerId.setText(customerData[0]);
        txt_name.setText(customerData[1]);
        txt_birthdate.setText(customerData[2]);
        txt_address.setText(customerData[3]);
        txt_mobile.setText(customerData[4]);
        txt_email.setText(customerData[5]);
        txt_type.setText(customerData[6]);
        txt_accountNo.setText(customerData[7]);
        txt_sortCode.setText(customerData[8]);
        txt_balance.setText(customerData[9]);
        txt_card.setText(customerData[10]);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_operation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_accountNo;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_birthdate;
    private javax.swing.JTextField txt_card;
    private javax.swing.JTextField txt_customerId;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_sortCode;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables
}
