/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ebank.views;

import com.ebank.controllers.CustomerPageController;
import static com.ebank.main.CommonFunctions.isValidRowSelection;
import static com.ebank.main.CommonFunctions.showMsg;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shan
 */
public class CustomerPage extends javax.swing.JFrame {

    private CustomerPageController controller;
    private DefaultTableModel customerTableModel;
    private String loggedInUser;

    /**
     * Creates new form CustomerPage
     *
     * @param loggedInUser currently logged in user's username
     */
    public CustomerPage(String loggedInUser) {
        initComponents();
        setLocationRelativeTo(null);
        controller = new CustomerPageController();
        customerTableModel = (DefaultTableModel) jtb_customerList.getModel();
        refreshCustomerRecords();
        this.loggedInUser = loggedInUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_customerList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer List Page");

        jPanel1.setBackground(java.awt.Color.cyan);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Page");
        jPanel1.add(jLabel1);

        jPanel4.setBackground(java.awt.Color.cyan);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btn_logout.setBackground(java.awt.Color.orange);
        btn_logout.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel4.add(btn_logout);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(java.awt.Color.pink);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 20));

        btn_add.setBackground(java.awt.Color.yellow);
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add);

        btn_edit.setBackground(java.awt.Color.yellow);
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel2.add(btn_edit);

        btn_delete.setBackground(java.awt.Color.yellow);
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        jPanel2.add(btn_delete);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jtb_customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Account No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_customerList);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        prepareEditCustomer();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        if (controller.logout(loggedInUser)) {
            new LoginPage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        new CustomerForm().setVisible(true);
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * Delete a record from the customer table model
     */
    private void deleteCustomer() {
        if (isValidRowSelection(jtb_customerList)) {
            int customerId = (int) customerTableModel.getValueAt(jtb_customerList.getSelectedRow(), 0);
            if (controller.syncCustomerDeleteOperation(customerId)) {
                customerTableModel.removeRow(jtb_customerList.getSelectedRow());
                showMsg(0, 0, "Customer record deleted");
            } else {
                showMsg(2, 2, "Unable to delete the record");
            }
        }
    }

    /**
     * Prepare a record to be edited from the table
     */
    private void prepareEditCustomer() {
        if (isValidRowSelection(jtb_customerList)) {
            int customerId = 0;
            new CustomerForm(customerId).setVisible(true);
        }
    }

    /**
     * Synchronize current customer data from the web service
     */
    private void refreshCustomerRecords() {
        String[][] customerObjects = controller.getCustomersData();
        for (String[] customerObject : customerObjects) {
            Object[] test = new Object[2];
            test[0] = customerObject[1];
            test[1] = customerObject[7];
            customerTableModel.addRow(test);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb_customerList;
    // End of variables declaration//GEN-END:variables
}
