/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ebank.views;

import com.ebank.controllers.EmployeeFormController;
import static com.ebank.main.CommonFunctions.showMsg;
import java.util.Arrays;

/**
 *
 * @author Shan
 */
public class EmployeeForm extends javax.swing.JFrame {

    EmployeePage parent;
    private EmployeeFormController controller;

    /**
     * Default constructor (for add operation)
     *
     * @param parent parent window
     */
    public EmployeeForm(EmployeePage parent) {
        controller = new EmployeeFormController();
        initComponents();
        customizelayout();
        setLocationRelativeTo(null);
        this.parent = parent;
    }

    /**
     * Overloaded constructor for edit operation
     *
     * @param employeeId employee record that needs to be edited
     * @param parent parent window
     */
    public EmployeeForm(int employeeId, EmployeePage parent) {
        controller = new EmployeeFormController();
        initComponents();
        customizelayout(employeeId);
        setLocationRelativeTo(null);
        this.parent = parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_operation = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_employeeId = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_position = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.cyan);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Details Form");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All fields are required");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(java.awt.Color.pink);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 20));

        btn_operation.setBackground(java.awt.Color.yellow);
        btn_operation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_operation.setText("Operation");
        btn_operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operationActionPerformed(evt);
            }
        });
        jPanel2.add(btn_operation);

        btn_cancel.setBackground(java.awt.Color.yellow);
        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(7, 0, 0, 15));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Employee Id: ");
        jPanel5.add(jLabel4);

        txt_employeeId.setColumns(9);
        txt_employeeId.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txt_employeeId.setEnabled(false);
        jPanel5.add(txt_employeeId);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 95, 5));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name: ");
        jPanel6.add(jLabel5);

        txt_name.setColumns(10);
        txt_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel6.add(txt_name);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Position: ");
        jPanel7.add(jLabel6);

        txt_position.setColumns(10);
        txt_position.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(txt_position);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Username: ");
        jPanel8.add(jLabel3);

        txt_username.setColumns(10);
        txt_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel8.add(txt_username);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 55, 5));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password: ");
        jPanel9.add(jLabel7);

        txt_password.setColumns(10);
        txt_password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel9.add(txt_password);

        jPanel3.add(jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel10);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operationActionPerformed
        doOperation();
    }//GEN-LAST:event_btn_operationActionPerformed

    /**
     * Perform add/edit operation
     */
    private void doOperation() {
        int employeeId = 0;
        try { // if employeeId is not an int value
            employeeId = Integer.parseInt(txt_employeeId.getText());
        } catch (Exception e) {
            employeeId = 0;
        }
        String name = txt_name.getText();
        String position = txt_position.getText();
        String username = txt_username.getText();
        String password = String.copyValueOf(txt_password.getPassword());

        // check for empty fields
        if (!name.equals("") && !position.equals("") && !username.equals("") && !password.equals("")) {
            if (controller.syncEmployeeAddEditOperation(employeeId, name, position, username, password)) {
                showMsg(0, 0, "Record successfully added/edited");
                this.dispose();
                parent.dispose();
                new EmployeePage().setVisible(true);
            } else {
                showMsg(2, 2, "Something went wrong");
            }
        } else {
            showMsg(1, 1, "Please make sure you have filled all the fields");
        }
    }

    /**
     * Customize layout according to add operation
     */
    private void customizelayout() {
        this.setTitle("Add new employee");
        btn_operation.setText("Add");
        txt_employeeId.setText("N/A");
    }

    /**
     * Customize layout according to edit operation
     *
     * @param employeeId employeeId of the record that needs to be edited
     */
    private void customizelayout(int employeeId) {
        this.setTitle("Edit employee");
        btn_operation.setText("Edit");
        String[] employeeData = controller.getEmployeeData(employeeId);
        txt_employeeId.setText(employeeData[0]);
        txt_name.setText(employeeData[1]);
        txt_position.setText(employeeData[2]);
        txt_username.setText(employeeData[3]);
        txt_password.setText(employeeData[4]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_operation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txt_employeeId;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
